name: cativerse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8
  card_swiper: ^3.0.1
  line_icons: ^2.0.3
  custom_clippers: ^2.0.0
  flutter_card_swiper: ^7.0.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  flutter_firebase_chat_core: ^1.6.8
  flutter_custom_clippers: ^2.1.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  image_cropper: ^9.1.0
  permission_handler: ^12.0.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/cats/
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"